
EXT_IP = '34.90.19.13'
INT_IP = '10.164.0.2'


ADMIN_PASSWORD = 'admin'

# # test bot
# TOKEN = '1042488699:AAFEsvgJXyEIR3REXrSAMZjQB-HClDnNE0U'


# main bot
TOKEN = '1490631920:AAGrR249tGpt8EUrQ1UMYcZ-VOiqOEuPNDQ'

WEBHOOK_LISTEN = INT_IP
WEBHOOK_PORT = 8443

WEBHOOK_SSL_CERT = "/home/rent_b/ssl/ssl.pem"
WEBHOOK_SSL_PRIV = "/home/rent_b/ssl/ssl_priv.pem"

IMAGE_FOLDER = 'photos'

DATA_UPDATE_TIME = 600 # sec
USER_DATA_UPDATE_TIME = 30 # sec
USER_DATA_OLD_TIME = 60 # sec

DB_USER = 'postgres'
DB_PASSWORD = 'SF899laxe_'
DB_DATABASE = 'rent'
DB_HOST = 'localhost'

FILTER_APP_HOST = INT_IP
FILTER_APP_PORT = 82